### ISSUE TITLE
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

### ISSUE THREAD

**Issue by wccccp** [diuzi/baichuan_chat_bot#2]
Traceback (most recent call last):
  File "/home/wangchenpeng/lib/python3.9/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/wangchenpeng/lib/python3.9/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/home/wangchenpeng/lib/python3.9/site-packages/gradio/blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/wangchenpeng/lib/python3.9/site-packages/gradio/utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "/home/wangchenpeng/lib/python3.9/site-packages/gradio/utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/wangchenpeng/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/wangchenpeng/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/wangchenpeng/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/wangchenpeng/lib/python3.9/site-packages/gradio/utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "/home/wangchenpeng/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/mnt1/wcp/baichuan/baichuan_chat_bot-master/src/ui/webui.py", line 166, in stream_chat
    with torch.cuda.amp.autocast(): model.generate(**generation_params)
  File "/home/wangchenpeng/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/wangchenpeng/lib/python3.9/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/wangchenpeng/lib/python3.9/site-packages/transformers/generation/utils.py", line 2524, in sample
    outputs = self(
  File "/home/wangchenpeng/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt1/wcp/baichuan/baichuan_chat_bot-master/src/model/modeling_baichuan.py", line 629, in forward
    outputs = self.model(
  File "/home/wangchenpeng/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt1/wcp/baichuan/baichuan_chat_bot-master/src/model/modeling_baichuan.py", line 521, in forward
    layer_outputs = decoder_layer(
  File "/home/wangchenpeng/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt1/wcp/baichuan/baichuan_chat_bot-master/src/model/modeling_baichuan.py", line 326, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/wangchenpeng/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt1/wcp/baichuan/baichuan_chat_bot-master/src/model/modeling_baichuan.py", line 206, in forward
    proj = self.W_pack(hidden_states)
  File "/home/wangchenpeng/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangchenpeng/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)

**Comment by diuzi** [comment]
cpu推理的吗

**Comment by wccccp** [comment]
> cpu推理的吗
gradio自动cpu推理，但是我没有更改代码呀 运行不起来

**Comment by diuzi** [comment]
这个代码不支持cpu推理，cpu推理需要fp32，可以在模型加载哪里改一下

**Comment by wccccp** [comment]
> 这个代码不支持cpu推理，cpu推理需要fp32，可以在模型加载哪里改一下

我的意思是我没有使用cpu推理... 代码自动加载为cpu推理了。。我也没有修改代码

**Comment by diuzi** [comment]
建议检查下torch版本和cuda环境
